-- AI 知识库模块表结构

CREATE TABLE IF NOT EXISTS `ai_knowledge_base` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '知识库名称',
  `code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '知识库编码',
  `description` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '知识库描述',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `vector_store_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pgvector' COMMENT '向量库类型',
  `embedding_model` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Embedding 模型',
  `document_count` int NOT NULL DEFAULT 0 COMMENT '文档数量',
  `chunk_count` int NOT NULL DEFAULT 0 COMMENT '切片数量',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_kb_tenant_code_deleted` (`tenant_id`, `code`, `deleted`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识库表，用于存储企业知识库的基本信息和配置';

CREATE TABLE IF NOT EXISTS `ai_data_source` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '数据源名称',
  `type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '数据源类型',
  `config_json` text COLLATE utf8mb4_unicode_ci COMMENT '数据源配置',
  `sync_enabled` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用同步',
  `last_sync_time` datetime DEFAULT NULL COMMENT '最后同步时间',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_ds_kb_tenant` (`knowledge_base_id`, `tenant_id`) USING BTREE,
  KEY `idx_ai_ds_tenant_type` (`tenant_id`, `type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据源表，用于存储知识库的数据来源信息（如文件、数据库、API 等）';

CREATE TABLE IF NOT EXISTS `ai_document` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `data_source_id` bigint DEFAULT NULL COMMENT '数据源编号',
  `title` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文档标题',
  `file_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件名',
  `file_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件类型',
  `file_size` bigint NOT NULL DEFAULT 0 COMMENT '文件大小',
  `object_key` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '对象存储 Key',
  `source_uri` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源地址',
  `content_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容哈希',
  `parse_status` tinyint NOT NULL DEFAULT 0 COMMENT '解析状态',
  `embedding_status` tinyint NOT NULL DEFAULT 0 COMMENT '向量化状态',
  `chunk_count` int NOT NULL DEFAULT 0 COMMENT '切片数量',
  `token_count` int NOT NULL DEFAULT 0 COMMENT 'Token 数量',
  `error_message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_doc_kb_tenant_parse_embedding` (`knowledge_base_id`, `tenant_id`, `parse_status`, `embedding_status`) USING BTREE,
  KEY `idx_ai_doc_data_source` (`data_source_id`) USING BTREE,
  KEY `idx_ai_doc_content_hash` (`content_hash`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档表，用于存储上传或同步的文档基本信息及状态';

CREATE TABLE IF NOT EXISTS `ai_document_chunk` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `document_id` bigint NOT NULL COMMENT '文档编号',
  `chunk_index` int NOT NULL COMMENT '切片序号',
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '切片内容',
  `content_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容哈希',
  `token_count` int NOT NULL DEFAULT 0 COMMENT 'Token 数量',
  `vector_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '向量编号',
  `metadata_json` text COLLATE utf8mb4_unicode_ci COMMENT '元数据',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_chunk_kb_doc_tenant_status` (`knowledge_base_id`, `document_id`, `tenant_id`, `status`) USING BTREE,
  KEY `idx_ai_chunk_vector_id` (`vector_id`) USING BTREE,
  KEY `idx_ai_chunk_content_hash` (`content_hash`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档切片表，用于存储文档解析后的 chunk 内容及向量信息';

CREATE TABLE IF NOT EXISTS `ai_sync_job` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `data_source_id` bigint DEFAULT NULL COMMENT '数据源编号',
  `job_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务类型',
  `trigger_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '触发类型',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `total_count` int NOT NULL DEFAULT 0 COMMENT '总数',
  `success_count` int NOT NULL DEFAULT 0 COMMENT '成功数',
  `fail_count` int NOT NULL DEFAULT 0 COMMENT '失败数',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `error_message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_sync_job_kb_tenant_status` (`knowledge_base_id`, `tenant_id`, `status`) USING BTREE,
  KEY `idx_ai_sync_job_data_source` (`data_source_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步任务表，用于记录数据源同步任务信息（全量/增量）';

CREATE TABLE IF NOT EXISTS `ai_sync_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `sync_job_id` bigint NOT NULL COMMENT '同步任务编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `data_source_id` bigint DEFAULT NULL COMMENT '数据源编号',
  `document_id` bigint DEFAULT NULL COMMENT '文档编号',
  `source_uri` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源地址',
  `action_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '操作类型',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `error_message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_sync_record_job_status` (`sync_job_id`, `status`) USING BTREE,
  KEY `idx_ai_sync_record_kb_tenant` (`knowledge_base_id`, `tenant_id`) USING BTREE,
  KEY `idx_ai_sync_record_document` (`document_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='同步记录表，用于记录每条数据在同步任务中的处理结果';

CREATE TABLE IF NOT EXISTS `ai_chat_conversation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `title` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会话标题',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `last_message_time` datetime DEFAULT NULL COMMENT '最后消息时间',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_conversation_user_kb_tenant` (`user_id`, `knowledge_base_id`, `tenant_id`) USING BTREE,
  KEY `idx_ai_conversation_kb_tenant` (`knowledge_base_id`, `tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问答会话表，用于记录用户发起的问答会话信息';

CREATE TABLE IF NOT EXISTS `ai_chat_message` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `conversation_id` bigint NOT NULL COMMENT '会话编号',
  `user_id` bigint DEFAULT NULL COMMENT '用户编号',
  `role` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息角色',
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息内容',
  `prompt_tokens` int NOT NULL DEFAULT 0 COMMENT '提示词 Token 数',
  `completion_tokens` int NOT NULL DEFAULT 0 COMMENT '回复 Token 数',
  `total_tokens` int NOT NULL DEFAULT 0 COMMENT '总 Token 数',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `error_message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_message_conversation_id` (`conversation_id`) USING BTREE,
  KEY `idx_ai_message_tenant_user` (`tenant_id`, `user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问答消息表，用于存储会话中的每条消息，包括用户提问和模型回答';

CREATE TABLE IF NOT EXISTS `ai_chat_citation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `message_id` bigint NOT NULL COMMENT '消息编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `document_id` bigint NOT NULL COMMENT '文档编号',
  `chunk_id` bigint NOT NULL COMMENT '切片编号',
  `score` decimal(10,6) DEFAULT NULL COMMENT '相关性分数',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `quote_text` text COLLATE utf8mb4_unicode_ci COMMENT '引用内容',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_citation_message_document_chunk` (`message_id`, `document_id`, `chunk_id`) USING BTREE,
  KEY `idx_ai_citation_kb_tenant` (`knowledge_base_id`, `tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='引用来源表，用于存储问答返回中引用的文档/Chunk 信息';
