CREATE TABLE IF NOT EXISTS `finance_invoice` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `invoice_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UPLOAD',
  `source_message_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_sender` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_received_time` datetime DEFAULT NULL,
  `file_id` bigint DEFAULT NULL,
  `file_url` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object_key` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `supplier_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_tax_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_date` datetime DEFAULT NULL,
  `due_date` datetime DEFAULT NULL,
  `currency` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `net_amount` decimal(18,2) DEFAULT NULL,
  `vat_amount` decimal(18,2) DEFAULT NULL,
  `gross_amount` decimal(18,2) DEFAULT NULL,
  `iban` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bic` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_account_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expense_category` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `business_desc` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `po_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ai_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NOT_RECOGNIZED',
  `ai_confidence` decimal(5,2) DEFAULT NULL,
  `ai_raw_result` mediumtext COLLATE utf8mb4_unicode_ci,
  `ai_summary` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ai_error_message` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `finance_review_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `risk_level` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NONE',
  `risk_flags` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '[]',
  `risk_summary` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approval_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT',
  `process_instance_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `process_definition_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookkeeping_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NOT_BOOKED',
  `payment_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NOT_PAID',
  `payment_time` datetime DEFAULT NULL,
  `payment_remark` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remark` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_finance_invoice_no` (`invoice_no`),
  KEY `idx_finance_supplier_invoice` (`supplier_name`, `invoice_no`),
  KEY `idx_finance_process_instance_id` (`process_instance_id`),
  KEY `idx_finance_approval_status` (`approval_status`),
  KEY `idx_finance_file_hash` (`file_hash`),
  KEY `idx_finance_create_time` (`create_time`),
  KEY `idx_finance_source_message` (`tenant_id`, `source_type`, `source_message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Finance invoice';

CREATE TABLE IF NOT EXISTS `finance_invoice_attachment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `invoice_id` bigint NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_url` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object_key` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `file_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attachment_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'INVOICE',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_finance_invoice_attachment_invoice` (`tenant_id`, `invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Finance invoice attachment';

CREATE TABLE IF NOT EXISTS `finance_supplier_payment_info` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `supplier_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `supplier_tax_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iban` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bic` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_account_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_invoice_id` bigint DEFAULT NULL,
  `last_invoice_id` bigint DEFAULT NULL,
  `last_used_time` datetime DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ENABLED',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_finance_supplier_name` (`supplier_name`),
  KEY `idx_finance_supplier_iban` (`supplier_name`, `iban`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Supplier payment info';

CREATE TABLE IF NOT EXISTS `finance_invoice_risk_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `rule_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rule_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` bit(1) NOT NULL DEFAULT b'1',
  `threshold_amount` decimal(18,2) DEFAULT NULL,
  `currency` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `risk_level` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_finance_risk_rule_code` (`tenant_id`, `rule_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Finance invoice risk rule';

INSERT IGNORE INTO `finance_invoice_risk_rule`
(`id`, `tenant_id`, `rule_code`, `rule_name`, `enabled`, `threshold_amount`, `currency`, `risk_level`, `description`, `creator`, `updater`)
VALUES
(920001, 0, 'AMOUNT_OVER_LIMIT', '金额超限', b'1', 3000.00, 'EUR', 'HIGH', 'EUR 含税金额超过 3000', 'admin', 'admin'),
(920002, 0, 'IBAN_CHANGED', 'IBAN 变化', b'1', NULL, NULL, 'HIGH', '同供应商历史 IBAN 与本次不一致', 'admin', 'admin'),
(920003, 0, 'NEW_SUPPLIER', '新供应商', b'1', NULL, NULL, 'MEDIUM', '供应商首次出现', 'admin', 'admin'),
(920004, 0, 'NO_PO', '无 PO', b'1', NULL, NULL, 'MEDIUM', '未填写 PO 号', 'admin', 'admin'),
(920005, 0, 'NO_CONTRACT', '无合同', b'1', NULL, NULL, 'LOW', '未填写合同号', 'admin', 'admin'),
(920006, 0, 'DUPLICATE_INVOICE', '重复发票', b'1', NULL, NULL, 'HIGH', '供应商、发票号、金额和日期重复', 'admin', 'admin');

INSERT IGNORE INTO `system_dict_type` (`id`, `name`, `type`, `status`, `creator`, `updater`) VALUES
(920101, '发票来源', 'finance_invoice_source_type', 0, 'admin', 'admin'),
(920102, '发票 AI 状态', 'finance_invoice_ai_status', 0, 'admin', 'admin'),
(920103, '发票财务确认状态', 'finance_invoice_review_status', 0, 'admin', 'admin'),
(920104, '发票审批状态', 'finance_invoice_approval_status', 0, 'admin', 'admin'),
(920105, '发票记账状态', 'finance_invoice_bookkeeping_status', 0, 'admin', 'admin'),
(920106, '发票付款状态', 'finance_invoice_payment_status', 0, 'admin', 'admin'),
(920107, '发票风险等级', 'finance_invoice_risk_level', 0, 'admin', 'admin'),
(920108, '发票费用类别', 'finance_invoice_expense_category', 0, 'admin', 'admin'),
(920109, '发票风险标记', 'finance_invoice_risk_flag', 0, 'admin', 'admin');

INSERT IGNORE INTO `system_dict_data` (`id`, `sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `creator`, `updater`) VALUES
(920201, 1, '手动上传', 'UPLOAD', 'finance_invoice_source_type', 0, 'primary', 'admin', 'admin'),
(920202, 2, '邮箱收票', 'EMAIL', 'finance_invoice_source_type', 0, 'info', 'admin', 'admin'),
(920203, 3, '手工录入', 'MANUAL', 'finance_invoice_source_type', 0, 'info', 'admin', 'admin'),
(920211, 1, '未识别', 'NOT_RECOGNIZED', 'finance_invoice_ai_status', 0, 'info', 'admin', 'admin'),
(920212, 2, '识别中', 'RECOGNIZING', 'finance_invoice_ai_status', 0, 'warning', 'admin', 'admin'),
(920213, 3, '已识别', 'RECOGNIZED', 'finance_invoice_ai_status', 0, 'success', 'admin', 'admin'),
(920214, 4, '识别失败', 'FAILED', 'finance_invoice_ai_status', 0, 'danger', 'admin', 'admin'),
(920221, 1, '待确认', 'PENDING', 'finance_invoice_review_status', 0, 'warning', 'admin', 'admin'),
(920222, 2, '已确认', 'CONFIRMED', 'finance_invoice_review_status', 0, 'success', 'admin', 'admin'),
(920223, 3, '已退回', 'REJECTED', 'finance_invoice_review_status', 0, 'danger', 'admin', 'admin'),
(920231, 1, '草稿', 'DRAFT', 'finance_invoice_approval_status', 0, 'info', 'admin', 'admin'),
(920232, 2, '待确认', 'WAIT_CONFIRM', 'finance_invoice_approval_status', 0, 'warning', 'admin', 'admin'),
(920233, 3, '审批中', 'APPROVING', 'finance_invoice_approval_status', 0, 'primary', 'admin', 'admin'),
(920234, 4, '已审批', 'APPROVED', 'finance_invoice_approval_status', 0, 'success', 'admin', 'admin'),
(920235, 5, '已驳回', 'REJECTED', 'finance_invoice_approval_status', 0, 'danger', 'admin', 'admin'),
(920236, 6, '已取消', 'CANCELED', 'finance_invoice_approval_status', 0, 'info', 'admin', 'admin'),
(920241, 1, '未记账', 'NOT_BOOKED', 'finance_invoice_bookkeeping_status', 0, 'warning', 'admin', 'admin'),
(920242, 2, '已记账', 'BOOKED', 'finance_invoice_bookkeeping_status', 0, 'success', 'admin', 'admin'),
(920251, 1, '未付款', 'NOT_PAID', 'finance_invoice_payment_status', 0, 'warning', 'admin', 'admin'),
(920252, 2, '已付款', 'PAID', 'finance_invoice_payment_status', 0, 'success', 'admin', 'admin'),
(920261, 1, '无风险', 'NONE', 'finance_invoice_risk_level', 0, 'info', 'admin', 'admin'),
(920262, 2, '低风险', 'LOW', 'finance_invoice_risk_level', 0, 'success', 'admin', 'admin'),
(920263, 3, '中风险', 'MEDIUM', 'finance_invoice_risk_level', 0, 'warning', 'admin', 'admin'),
(920264, 4, '高风险', 'HIGH', 'finance_invoice_risk_level', 0, 'danger', 'admin', 'admin'),
(920271, 1, '采购', 'PURCHASE', 'finance_invoice_expense_category', 0, 'primary', 'admin', 'admin'),
(920272, 2, '物流', 'LOGISTICS', 'finance_invoice_expense_category', 0, 'primary', 'admin', 'admin'),
(920273, 3, '服务', 'SERVICE', 'finance_invoice_expense_category', 0, 'primary', 'admin', 'admin'),
(920274, 4, '差旅', 'TRAVEL', 'finance_invoice_expense_category', 0, 'primary', 'admin', 'admin'),
(920275, 5, '仓储', 'WAREHOUSE', 'finance_invoice_expense_category', 0, 'primary', 'admin', 'admin'),
(920276, 6, '其他', 'OTHER', 'finance_invoice_expense_category', 0, 'info', 'admin', 'admin'),
(920281, 1, '新供应商', 'NEW_SUPPLIER', 'finance_invoice_risk_flag', 0, 'warning', 'admin', 'admin'),
(920282, 2, 'IBAN 变化', 'IBAN_CHANGED', 'finance_invoice_risk_flag', 0, 'danger', 'admin', 'admin'),
(920283, 3, '无 PO', 'NO_PO', 'finance_invoice_risk_flag', 0, 'warning', 'admin', 'admin'),
(920284, 4, '无合同', 'NO_CONTRACT', 'finance_invoice_risk_flag', 0, 'warning', 'admin', 'admin'),
(920285, 5, '重复发票', 'DUPLICATE_INVOICE', 'finance_invoice_risk_flag', 0, 'danger', 'admin', 'admin'),
(920286, 6, '金额超限', 'AMOUNT_OVER_LIMIT', 'finance_invoice_risk_flag', 0, 'danger', 'admin', 'admin'),
(920287, 7, 'VAT 异常', 'VAT_ABNORMAL', 'finance_invoice_risk_flag', 0, 'warning', 'admin', 'admin'),
(920288, 8, '币种异常', 'CURRENCY_ABNORMAL', 'finance_invoice_risk_flag', 0, 'warning', 'admin', 'admin');

INSERT INTO `system_menu`
(`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`)
VALUES
(920600, 'AI财务助手', '', 1, 12, 0, '/finance', 'ep:money', NULL, NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920601, '发票上传', 'finance:invoice:create', 2, 1, 920600, 'invoice/upload', 'ep:upload', 'finance/invoice/index', 'FinanceInvoiceUpload', 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920602, '待确认发票', 'finance:invoice:confirm', 2, 2, 920600, 'invoice/confirm', 'ep:document-checked', 'finance/invoice/index', 'FinanceInvoiceConfirm', 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920603, '发票台账', 'finance:invoice:query', 2, 3, 920600, 'invoice', 'ep:tickets', 'finance/invoice/index', 'FinanceInvoiceLedger', 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920620, '发票创建', 'finance:invoice:create', 3, 1, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920621, '发票编辑', 'finance:invoice:update', 3, 2, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920622, '发票删除', 'finance:invoice:delete', 3, 3, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920623, '发票查询', 'finance:invoice:query', 3, 4, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920624, '发票导出', 'finance:invoice:export', 3, 5, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920625, 'AI识别', 'finance:invoice:recognize', 3, 6, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920626, '财务确认', 'finance:invoice:confirm', 3, 7, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920627, '提交审批', 'finance:invoice:submit', 3, 8, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920628, '更新付款状态', 'finance:invoice:payment-update', 3, 9, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920629, '更新记账状态', 'finance:invoice:book-update', 3, 10, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(920630, '风险规则配置', 'finance:invoice:rule', 3, 11, 920603, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `permission` = VALUES(`permission`),
  `type` = VALUES(`type`),
  `sort` = VALUES(`sort`),
  `parent_id` = VALUES(`parent_id`),
  `path` = VALUES(`path`),
  `icon` = VALUES(`icon`),
  `component` = VALUES(`component`),
  `component_name` = VALUES(`component_name`),
  `status` = VALUES(`status`),
  `visible` = VALUES(`visible`),
  `keep_alive` = VALUES(`keep_alive`),
  `always_show` = VALUES(`always_show`),
  `updater` = VALUES(`updater`),
  `update_time` = VALUES(`update_time`),
  `deleted` = VALUES(`deleted`);
