CREATE TABLE IF NOT EXISTS `ai_chat_question_cache` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `department_id` bigint NOT NULL DEFAULT 0 COMMENT '部门编号',
  `knowledge_base_id` bigint NOT NULL COMMENT '知识库编号',
  `user_id` bigint DEFAULT NULL COMMENT '首次提问用户编号',
  `question` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始问题',
  `normalized_question` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '归一化问题',
  `question_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '问题哈希',
  `answer` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '缓存回答',
  `model` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '模型名称',
  `prompt_tokens` int NOT NULL DEFAULT 0 COMMENT '提示词 Token 数',
  `completion_tokens` int NOT NULL DEFAULT 0 COMMENT '回复 Token 数',
  `total_tokens` int NOT NULL DEFAULT 0 COMMENT '总 Token 数',
  `latency_ms` bigint NOT NULL DEFAULT 0 COMMENT '原模型调用耗时，单位毫秒',
  `citation_snapshot_json` longtext COLLATE utf8mb4_unicode_ci COMMENT '引用来源快照 JSON',
  `hit_count` int NOT NULL DEFAULT 0 COMMENT '缓存命中次数',
  `last_hit_time` datetime DEFAULT NULL COMMENT '最后命中时间',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ai_question_cache_scope_hash` (`tenant_id`, `department_id`, `knowledge_base_id`, `question_hash`, `deleted`) USING BTREE,
  KEY `idx_ai_question_cache_kb_tenant` (`knowledge_base_id`, `tenant_id`) USING BTREE,
  KEY `idx_ai_question_cache_last_hit` (`tenant_id`, `knowledge_base_id`, `last_hit_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问答问题缓存表，用于复用已生成且带引用的答案';
